### ISSUE TITLE
Error ERR_STREAM_WRITE_AFTER_END on second run

### ISSUE THREAD

**Issue by gitowiec** [feross/multistream#54]
I have this code:
```typescript

  async run(unsortedCsvFilesList: string[]): Promise<string> {
    const csvFilesList = unsortedCsvFilesList.sort(naturalCompare);
    const jobId = getReqId();
    const jobUnzipTargetFilePath = `${this.defaultTransformerSourceFilePath}/${jobId}`;

    const Multistream = require('multistream');
    const fullFileNamePathsToStream = (filenamePaths: string[]) => {
      return new Multistream(filenamePaths.map(path => fs.createReadStream(path)));
    };

    const filesStream = fullFileNamePathsToStream(csvFilesList.map(fileName => `${jobUnzipTargetFilePath}/${fileName}`));

    await mkdirPromised(`${this.defaultTransformerDestinationFilePath}/${jobId}`, { recursive: true });

    const { getSchemaTransformer, stringifier } = require('transformers/src');

    try {

      getSchemaTransformer('mBiznesExCsv')
        .reduce((acc, transformer) => acc.pipe(transformer), filesStream)
        .pipe(stringifier)
        .pipe(
          fs.createWriteStream(`${this.defaultTransformerDestinationFilePath}/${jobId}/download.csv`),
          // await getDestinationStream(
          // `${this.defaultTransformerDestinationFilePath}/${jobId}/download.csv`)
        );
      // filesStream.destroy();
    } catch (error) {
      this.logger.error(error,'oh crap');
    }

    return jobId;
  }

```
It is the method stored in use case class inside tsoa NodeJS application with InversifyJS.
`getSchemaTransformer` returns transformer made with mississippi module. `stringifier` is `csv-stringify` module.

It works ok for the first time.

But every second run it crashes with
```
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:248:12)
    at Parser.Writable.write (_stream_writable.js:296:5)
    at MultiStream.ondata (/home/user/workspace/bank-statement-csv-processor/node_modules/multistream/node_modules/readable-stream/lib/_stream_readable.js:681:20)
    at MultiStream.emit (events.js:198:13)
    at addChunk (/home/user/workspace/bank-statement-csv-processor/node_modules/multistream/node_modules/readable-stream/lib/_stream_readable.js:298:12)
    at readableAddChunk (/home/user/workspace/bank-statement-csv-processor/node_modules/multistream/node_modules/readable-stream/lib/_stream_readable.js:280:11)
    at MultiStream.Readable.push (/home/user/workspace/bank-statement-csv-processor/node_modules/multistream/node_modules/readable-stream/lib/_stream_readable.js:241:10)
    at MultiStream._forward (/home/user/workspace/bank-statement-csv-processor/node_modules/multistream/index.js:56:28)
    at ReadStream.onReadable (/home/user/workspace/bank-statement-csv-processor/node_modules/multistream/index.js:108:12)
    at ReadStream.emit (events.js:198:13)
    at emitReadable_ (_stream_readable.js:554:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
error Command failed with exit code 1.      
``` 
I tried to pipe the output to process.stdout, I tried to require('multistream') inside the method body.

I don't know how to debug this issue. More, the try{}catch clause does not catch this error - I don't know why.

Please help

**Comment by gitowiec** [comment]
I was able to establish the culprit of this error with "divide and conquer" :) . It is not multistream but node-csv-stringify https://github.com/adaltas/node-csv-stringify/issues/119
Thanks for support
